sudo: false
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 12
before_install:
  - npm i -g npm@^6.12.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run coverage
after_success:
  - npm run check-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
